name: Integration continue

on:
  push:
    tags:
      - 'v*.*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main

  workflow_dispatch:

permissions:
    contents: write
jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Launch project
        uses: ./.github/actions
      - name: Build
        run: npm run build -w backend
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Launch project
        uses: ./.github/actions
      - name: Build
        run: npm run build -w frontend
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Launch project
        uses: ./.github/actions
      - name: Test
        run: npm run test -w backend
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Launch project
        uses: ./.github/actions
      - name: Test
        run: npm run test -w frontend
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Launch project
        uses: ./.github/actions
      - name: Lint
        run: npm run lint -w backend
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Launch project
        uses: ./.github/actions
      - name: Lint
        run: npm run lint -w frontend
  create-archive-release:
    runs-on: ubuntu-latest
    steps:
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig .husky LICENSE action.yml'
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          draft: false
          prerelease: false
          name: test release 3
          tag_name: v1
          file: 'release.zip'

